version: '3.8'

services:
  portale-visitatori:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATA_DIR=/app/data
      - FGT_API_URL=${FGT_API_URL}
      - FGT_API_KEY=${FGT_API_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    restart: unless-stopped